### ISSUE TITLE
Index.js is missing in npm package, causing build to fail

### ISSUE THREAD

**Issue by alexbeletsky** [primus/ejson#11]
Package.json,

```
  "dependencies": {
    "ejson": "^2.1.0",
    "faye-websocket": "^0.10.0"
  },
```

Source,

```js
var EJSON = require('ejson');
```

Running tests,

```
 npmt

> ddp-server-event@1.0.1 test /Users/alexanderbeletsky/Development/Projects/ddp-server-event
> ./node_modules/mocha/bin/mocha

module.js:338
    throw err;
          ^
Error: Cannot find module 'ejson'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/alexanderbeletsky/Development/Projects/ddp-server-event/source/index.js:5:13)
```

The `package.json` has reference to `index.js` which is missing in package itself,

<img width="565" alt="screenshot 2015-08-10 11 13 32" src="https://cloud.githubusercontent.com/assets/304929/9165687/e0a86842-3f50-11e5-89fb-d606144413e1.png">

**Comment by 3rd-Eden** [comment]
Bumped dependencies rebuild and republished. Confirmed that index.js is now present. Not sure why on earth it was gone as it's part of the `npm prepublish` lifecycle. But thanks for reporting.
