### ISSUE TITLE
EJSON produces a TypeError in momentjs

### ISSUE THREAD

**Issue by idstein** [primus/ejson#15]
`moment.js:129 Uncaught TypeError: m._d.getTime is not a function(…)
valid__isValid @ moment.js:129
moment_valid__isValid @ moment.js:3215
toJSON @ moment.js:3211
EJSON.stringify @ ejson.js:343
stringify @ reactive-dict.js:6
set @ reactive-dict.js:61`

Some test code to produce the issue

`Session.set('date', moment() )`

The root cause seems to be that EJSON changes the internal date object of momentjs. That makes it impossible for momentjs to properly implement its own toJSON serialization.

**Comment by lpinca** [comment]
Hi,
we are basically only bundling https://github.com/meteor/meteor/blob/devel/packages/ejson/ejson.js so I think you should report the issue to Meteor as well.

**Comment by idstein** [comment]
Thanks for that hint! I will address it there.
