### ISSUE TITLE
Remove underscore.js

### ISSUE THREAD

**Issue by thesunny** [primus/ejson#37]
72% of the size of EJSON is underscore yet only a small portion of it is used.

By removing the underscore requirement and replacing it with only the specific methods we need from `lodash`, we can reduce the size of EJSON by more than half.

https://bundlephobia.com/result?p=ejson@2.1.2

This won't affect the weight for users that are already using `underscore` very much and it would remove loading all of `underscore` for `lodash` users. And if you don't use either, it reduces the weight to a minimum.

For example, instead of

```js
import _ from 'underscore'
_.has(object, path)
```

We can do

```js
import has from 'lodash/has'
has(object, path)
```

I can make a PR if you are in agreement.

**Comment by lpinca** [comment]
It seems the dependency from underscore was removed in https://github.com/meteor/meteor/commit/c6bddb331a8fd8c24336c6a7232406a3f108a6b5#diff-91868601b1609aa65a70a2ee9d2ec610

There is a script to pull the required js files from upstream (`npm run update`) but some work is also needed to remove underscore from

- https://github.com/primus/ejson/blob/master/source.js#L31
- https://github.com/primus/ejson/blob/master/build.js#L29
