### ISSUE TITLE
Add proper conversion table

### ISSUE THREAD

**Issue by totty90** [primus/ejson#9]
For example:

 - "a" is converted to '"a"'
 - 3 is converted to '3'

...

**Comment by 3rd-Eden** [comment]
Why? It's just JSON with a flavor.

**Comment by totty90** [comment]
I've seen that you serialize date as `'{$date: 0}'`. Therefore I expected the number to be `'{$number: 3}'` instead of `'3'`. I don't have to test on my own how your lib works, that's why docs are useful.

**Comment by 3rd-Eden** [comment]
@totty90 Well, as the docs state it's just a wrapper around Meteor's EJSON, so I've linked to their documentation which explains how it works: http://docs.meteor.com/#/full/ejson in the README.md of this project (these docs also state how they are serialized).
